# ================= 全局设置 (保持原样) =================
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
mode: rule
ipv6: true
unified-delay: true
tcp-concurrent: true
log-level: warning
find-process-mode: 'off'
# interface-name: veth-mihomo
client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false

# 配置文件持久化设置
profile:
  store-selected: true
  store-fake-ip: true

# ================= 控制面板 (修正路径) =================
external-controller: 0.0.0.0:9090
secret: ""
external-ui: "ui" 

# ================= 机场订阅 (修正语法) =================
#proxy-providers:
#  Airport1:
#   url: "https://xxx"
#    type: http
#    interval: 86400
#    path: ./providers/Airport1.yaml 
#    proxy: 直连 
#    health-check:
#      enable: true
#      url: http://cp.cloudflare.com/generate_204
#      interval: 300
#    override:
#      # 强制将所有下载的节点 packet-encoding 设为空，解决 xudp 导致的无延迟问题
#      packet-encoding: ""
#      client-fingerprint: "chrome"
# ================= 节点信息 (保持原样) =================
proxies:
  - {name: 直连, type: direct, udp: true}
# ================= 嗅探 (保持原样) =================
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "rule-set:private_domain,cn_domain"
    - "+.goofish.com"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"
    - "+.wechat.com"
    - "+.qpic.cn"
    - "+.qq.com"
    - "+.wechatapp.com"
    - "+.vivox.com"
    - "+.oray.com"
    - "+.sunlogin.net"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "+.wql.us"
    - "+.keywordsstudios.cn"

# ================= 入站 Tun (保持原样) =================
tun:
  enable: true
  stack: mips
  device: tun0
  dns-hijack: 
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: false
  auto-detect-interface: true
  mtu: 1380

# ================= DNS模块 (注入优化) =================
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # 建议改为标准 198.18 段，原 28.0.0.1 可能会冲突
  fake-ip-filter-mode: blacklist
  
  # 【优化】让国内域名不过 Fake-IP，直接返回真实 IP，配合直连规则
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "*.lan"
    - "*.local"
    - "+.services.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
    - "time.*.com"
    - "+.pool.ntp.org"
    - "+.ntp.tencent.com"
    - "+.ntp1.aliyun.com"
    - "+.ntp.ntsc.ac.cn"
    - "+.cn.ntp.org.cn"
    - "*.microsoftonline.com"
    - "*.wql.us"
    - "*.microsoft.com"
    - "*.keywordsstudios.cn"
    - "geosite:cn" # 额外增加 geosite 库的国内域名

  # 【新增】DNS 分流策略：国内域名强制用国内 DNS 解析
  nameserver-policy:
    "geosite:cn,private":
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    "rule-set:cn_domain":
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
  default-nameserver:
    - 223.5.5.5
    - 1.12.12.12
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
  nameserver:
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query
  fallback:
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
        - 240.0.0.0/4

# ================= 出站策略 (保持原样) =================
pr: &pr {type: select, proxies: [♻️ 自动选择, ♻️ 香港自动, ♻️ 日本自动, ♻️ 美国自动, ♻️ 台湾自动, ♻️ 新加坡自动, 🌐 手动选择,  直连]}

proxy-groups:
  - {name: 🚀 默认代理, <<: *pr, default: ♻️ 自动选择}
  - {name: ✈️ MyUrl, <<: *pr, default: ♻️ 自动选择}
  - {name: 🍀 Google-Work, <<: *pr, default: ♻️ 自动选择}
  - {name: 📹 YouTube, <<: *pr, default: ♻️ 自动选择}
  - {name: 🎵 TikTok, <<: *pr, default: ♻️ 美国自动}
  - {name: 🎥 NETFLIX, <<: *pr, default: ♻️ 新加坡自动}
  - {name: 🐬 OneDrive, <<: *pr, default: ♻️ xsus}
  - {name: 🚀 Oversea-Game, <<: *pr, default: 直连}
  - {name: 🎯 直连, type: select, proxies: [直连, 🚀 默认代理]}
  - {name: 🚫 AD-BLOCK, type: select, proxies: [REJECT, DIRECT]}
  - {name: 🐟 漏网之鱼, <<: *pr, default: 🚀 默认代理}
  - {name: 🌐 手动选择, type: select, include-all: true, use: [Airport1]}
  - {name: ♻️ 香港自动, type: url-test, use: [Airport1], include-all: true, tolerance: 50, interval: 150, url: "http://cp.cloudflare.com/generate_204", filter: "(?=.*(hk|港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美|a1|aws|acck|cc|rn|ak|xueshan)).)*$"}
  - {name: ♻️ 日本自动, type: url-test, use: [Airport1], include-all: true, tolerance: 50, interval: 150, url: "http://cp.cloudflare.com/generate_204", filter: "(?=.*(jp|日|JP|(?i)Japan))^((?!(港|台|韩|新|美|尼|a1|aws|acck|cc|rn|ak|xueshan)).)*$"}
  - {name: ♻️ 台湾自动, type: url-test, use: [Airport1], include-all: true, tolerance: 50, interval: 150, url: "http://cp.cloudflare.com/generate_204", filter: "(?=.*(tw|台|TW|(?i)Taiwan))^((?!(港|日|韩|新|美|a1|aws|acck|cc|rn|ak|lxueshan)).)*$"}
  - {name: ♻️ 新加坡自动, type: url-test, use: [Airport1], include-all: true, tolerance: 50, interval: 150, url: "http://cp.cloudflare.com/generate_204", filter: "(?=.*(sg|狮城|新|SG|(?i)Singapore))^((?!(港|台|日|韩|美|a1|aws|acck|cc|rn|ak|xueshan)).)*$"}
  - {name: ♻️ 美国自动, type: url-test, use: [Airport1], include-all: true, tolerance: 50, interval: 150, url: "http://cp.cloudflare.com/generate_204", filter: "(?=.*(美|US|us|(?i)States|America))^((?!(港|台|日|韩|新|Aus|AUS|澳|au|a1|aws|acck|ak|xueshan)).)*$"}
  - {name: ♻️ 自动选择, type: url-test, use: [Airport1], include-all: true, tolerance: 50, interval: 150, url: "http://cp.cloudflare.com/generate_204", filter: "^((?!(直连|home|a1|aws|acck|cc|rn|ak|xueshan)).)*$"}

# ================= 规则集 (保持原样) =================
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
  domain_text: &domain_text {type: http, interval: 86400, behavior: domain, format: yaml}

rule-providers:
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  myurl: { <<: *class, url: "https://raw.githubusercontent.com/wuquanlin/proxyrules/refs/heads/main/mihomo/mihomo-myurl.yaml"}
  myurl_direct: {<<: *class, url: "https://raw.githubusercontent.com/wuquanlin/proxyrules/refs/heads/main/mihomo/mihomo-direct.yaml"}
  bybit_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/bybit.mrs"}
  bitget: { <<: *domain_text, url: "https://raw.githubusercontent.com/wuquanlin/proxyrules/refs/heads/main/mihomo/bitget.yaml"}
  blocked_url: { <<: *domain_text, url: "https://raw.githubusercontent.com/wuquanlin/proxyrules/refs/heads/main/mihomo/blocked_url.yaml"}
  google-work: { <<: *class, url: "https://raw.githubusercontent.com/wuquanlin/proxyrules/refs/heads/main/mihomo/mihomo-gg-work.yaml"}
  ai: {  <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-chat-!cn.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  steam_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  disney_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/apple.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  category-ads-all: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ads-all.mrs"}
  category-ads-all@ads: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ads-all@ads.mrs"}
  category-ads-ir: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ads-ir.mrs"}
  category-ads: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ads.mrs"}
  category-ads@ads: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ads@ads.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}

# ================= 规则匹配 (注入优化) =================
rules:
  - AND,((NETWORK,UDP),(DST-PORT,443),(DOMAIN-SUFFIX,goofish.com)),DIRECT
  - AND,((NETWORK,UDP),(DST-PORT,443),(DOMAIN-SUFFIX,taobao.com)),DIRECT
  - AND,((NETWORK,UDP),(DST-PORT,443),(DOMAIN-SUFFIX,alicdn.com)),DIRECT
  - AND,((NETWORK,UDP),(DST-PORT,443),(GEOSITE,cn)),DIRECT
  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT # 拦截 QUIC，强制回退 TCP
  - IP-CIDR,10.0.0.0/24,DIRECT
  - IP-CIDR,192.168.6.0/24,DIRECT
  - AND,((DOMAIN-SUFFIX,netflix.com),(NETWORK,UDP)),REJECT
  - RULE-SET,private_domain,直连
  - RULE-SET,myurl,✈️ MyUrl
  - RULE-SET,myurl_direct,🎯 直连
  - RULE-SET,cn_domain,🎯 直连
  - RULE-SET,cn_ip,🎯 直连
  - GEOIP,CN,🎯 直连
  - GEOIP,PRIVATE,🎯 直连
  - RULE-SET,apple_domain,🎯 直连
  - RULE-SET,bitget,🚀 默认代理
  - RULE-SET,bybit_domain,♻️ 日本自动
  - RULE-SET,blocked_url,🚫 AD-BLOCK
  - RULE-SET,category-ads-all,🚫 AD-BLOCK
  - RULE-SET,category-ads-all@ads,🚫 AD-BLOCK
  - RULE-SET,category-ads-ir,🚫 AD-BLOCK
  - RULE-SET,category-ads,🚫 AD-BLOCK
  - RULE-SET,category-ads@ads,🚫 AD-BLOCK
  - RULE-SET,github_domain,🚀 默认代理
  - RULE-SET,steam_domain,🚀 Oversea-Game
  - RULE-SET,youtube_domain,📹 YouTube
  - RULE-SET,google-work,🍀 Google-Work
  - RULE-SET,onedrive_domain,🐬 OneDrive
  - RULE-SET,microsoft_domain,🐬 OneDrive
  - RULE-SET,tiktok_domain,🎵 TikTok
  - RULE-SET,netflix_domain,🎥 NETFLIX
  - RULE-SET,disney_domain,🎥 NETFLIX
  - RULE-SET,speedtest_domain,🚀 默认代理
  - RULE-SET,telegram_domain,🚀 默认代理  
  - RULE-SET,paypal_domain,🚀 默认代理
  - RULE-SET,ai,🚀 默认代理
  - RULE-SET,telegram_ip,🚀 默认代理,no-resolve
  - RULE-SET,netflix_ip,🎥 NETFLIX,no-resolve
  - RULE-SET,gfw_domain,🚀 默认代理
  - RULE-SET,geolocation-!cn,🚀 默认代理
  - MATCH,🐟 漏网之鱼
